### ISSUE TITLE
Future Dates

### ISSUE THREAD

**Issue by PraveenBiradar** [atmulyana/bootstrap-datetime-week-picker#1]
Currently the calendar is allowing to select future dates..is it possible to disable future dates?

**Comment by atmulyana** [comment]
Use endDate option. My datepicker is based on another project that is documented at  https://bootstrap-datepicker.readthedocs.io/en/stable/options.htmlMost options should still work.
Regards,
AT Mulyana
    On Monday, 13 May 2019, 8:18:27 pm GMT+8, PraveenBiradar <notifications@github.com> wrote:  
 
 
Currently the calendar is allowing to select future dates..is it possible to disable future dates?
